#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# Set initial border color
bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"

bspc config border_width         3
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a "anytype" desktop='^2'

## AutoStart
sxhkd &
nitrogen --set-scaled $HOME/Pictures/Backgrounds/Sun\ Over\ Dunes.jpeg &
polybar &
picom &
greenclip daemon &
blueman-applet &
numlockx &
discord --start-minimized &
dunst &
anytype &
