#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d      

# Set initial border color
bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#8AB4F8"
bspc config presel_feedback_color "#6272a4"

bspc config border_width         4
bspc config window_gap          17

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

## Applications rule
bspc rule -a "stacer" state=floating

## AutoStart
$HOME/.config/bspwm/startup &
