#! /bin/sh

## BSPWM Config
bspc monitor -d        

## Set initial border color
bspc config normal_border_color "#515860"
bspc config active_border_color "#FF69B4"
bspc config focused_border_color "#1793D1"
bspc config presel_feedback_color "#3AB1F5"

bspc config border_width         4
bspc config window_gap          17

bspc config split_ratio          0.5

## Applications rule
# bspc rule -a "steam" desktop=^6
bspc rule -a "stacer" state=floating
bspc rule -a "scrcpy" state=floating
# bspc rule -a "Brave-browser" desktop=^1
bspc rule -a "Code" desktop=^3 follow=true
# bspc rule -a "Pcmanfm" desktop=^2 follow=true
bspc rule -a "discord" desktop=^5 follow=true
# bspc rule -a "VSCodium" desktop=^3 follow=true
bspc rule -a "Gnome-calculator" state=floating
# bspc rule -a "Alacritty" desktop=^2 follow=true
bspc rule -a "UnrealEditor" desktop=^4 follow=false
bspc rule -a "Com.github.sgpthomas.hourglass" state=floating
# bspc rule -a "Protonvpn-app" state=floating desktop=^7 follow=false
bspc rule -a "Protonvpn-app" state=floating
# bspc rule -a "SimpleScreenRecorder" state=floating desktop=^8 follow=true
bspc rule -a "SimpleScreenRecorder" state=floating






##----------------##
## System Startup ##
##----------------##
pkill sxhkd
sxhkd &

pkill protonvpn-app
protonvpn-app &

pkill picom
picom &

pkill dunst
dunst &

xsetroot -cursor_name left_ptr &

pkill -f /usr/lib/xfce-polkit/xfce-polkit
/usr/lib/xfce-polkit/xfce-polkit &

pkill -f $HOME/.config/dunst/batteryStatus
$HOME/.config/dunst/batteryStatus &

nitrogen --restore &

xinput set-prop  pointer:2.4G\ Mouse libinput\ Accel\ Profile\ Enabled 0 1 0 &
xinput set-prop PixArt\ Lenovo\ USB\ Optical\ Mouse libinput\ Accel\ Profile\ Enabled 0 1 0 &

##------------##
## Essentials ##
##------------##
pkill polybar
polybar &

pkill nm-applet
nm-applet &

pkill greenclip
greenclip daemon &

pkill -f optimus-manager-qt
optimus-manager-qt &

##-------------##
## Application ##
##-------------##
pkill Discord
discord --start-minimized &
