#! /bin/sh

## BSPWM Config
bspc monitor -d         

## Set initial border color
bspc config normal_border_color "#515860"
bspc config active_border_color "#FF69B4"
bspc config focused_border_color "#1793D1"
bspc config presel_feedback_color "#3AB1F5"

bspc config border_width         4
bspc config window_gap          8

bspc config split_ratio          0.5

## Applications rule
# bspc rule -a "steam" desktop=^7
bspc rule -a "stacer" state=floating
bspc rule -a "scrcpy" state=floating
# bspc rule -a "Brave-browser" desktop=^1
bspc rule -a "Code" desktop=^4 follow=true
# bspc rule -a "Pcmanfm" desktop=^2 follow=true
bspc rule -a "discord" desktop=^6 follow=true
# bspc rule -a "VSCodium" desktop=^4 follow=true
bspc rule -a "Gnome-calculator" state=floating
# bspc rule -a "Alacritty" desktop=^3 follow=true
bspc rule -a "UnrealEditor" desktop=^5 follow=false
bspc rule -a "UE4Editor" desktop=^5 follow=false
bspc rule -a "com.github.sgpthomas.hourglass" state=floating
# bspc rule -a "Protonvpn-app" state=floating desktop=^8 follow=false
bspc rule -a "Protonvpn-app" state=floating
# bspc rule -a "SimpleScreenRecorder" state=floating desktop=^9 follow=true
bspc rule -a "SimpleScreenRecorder" state=floating
bspc rule -a "Signal" state=floating
bspc rule -a "unityhub" state=floating





##----------------------##
## Drawing Tablet setup ##
##----------------------##
# Stylus
xsetwacom set "HUION HUION Tablet_H1060P Pen stylus" Button 1 "button +1"
xsetwacom set "HUION HUION Tablet_H1060P Pen stylus" Button 2 "button +2"
xsetwacom set "HUION HUION Tablet_H1060P Pen stylus" Button 3 "button +3"

# Tablet
xsetwacom set "HUION HUION Tablet_H1060P Pad pad" Button 1 "key h"
xsetwacom set "HUION HUION Tablet_H1060P Pad pad" Button 2 "key k"
xsetwacom set "HUION HUION Tablet_H1060P Pad pad" Button 3 "key 1"
xsetwacom set "HUION HUION Tablet_H1060P Pad pad" Button 8 "key 2"
xsetwacom set "HUION HUION Tablet_H1060P Pad pad" Button 9 "key 3"
xsetwacom set "HUION HUION Tablet_H1060P Pad pad" Button 10 "key 4"
xsetwacom set "HUION HUION Tablet_H1060P Pad pad" Button 11 "key 5"
xsetwacom set "HUION HUION Tablet_H1060P Pad pad" Button 12 "key 6"
xsetwacom set "HUION HUION Tablet_H1060P Pad pad" Button 13 "key 7"
xsetwacom set "HUION HUION Tablet_H1060P Pad pad" Button 14 "key 0"
xsetwacom set "HUION HUION Tablet_H1060P Pad pad" Button 15 "key ctrl z"
xsetwacom set "HUION HUION Tablet_H1060P Pad pad" Button 16 "key ctrl shift z"





##----------------##
## System Startup ##
##----------------##
pkill sxhkd
sxhkd &

pkill protonvpn-app
protonvpn-app &

pkill picom
picom &

pkill dunst
dunst &

xsetroot -cursor_name left_ptr &

pkill -f /usr/lib/xfce-polkit/xfce-polkit
/usr/lib/xfce-polkit/xfce-polkit &

pkill -f $HOME/.config/dunst/batteryStatus
$HOME/.config/dunst/batteryStatus &

nitrogen --restore &

xinput set-prop SINOWEALTH\ 2.4G\ Wireless\ Receiver libinput\ Accel\ Profile\ Enabled 0 1 0

##------------##
## Essentials ##
##------------##
pkill polybar
polybar &

pkill nm-applet
nm-applet &

pkill greenclip
greenclip daemon &

pkill -f optimus-manager-qt
optimus-manager-qt &

##-------------##
## Application ##
##-------------##
pkill Discord
discord --start-minimized &

pkill signal-desktop
signal-desktop &

pkill anytype
anytype &
