#!/bin/sh

while true; do
	battery_level=`acpi -b | grep -P -o '[0-9]+(?=%)'`
	## IF battery is less then 25%
	if [ $battery_level -le 25 ]
	then
    	    notify-send "Battery low" "Battery level is ${battery_level}%!"
	fi
	## Sleep for 1 sec
	sleep 1;
done
