#!/bin/sh

############
## System ##
############
pkill sxhkd
sxhkd &

pkill picom
picom &

pkill dunst
dunst &

numlockx &

xsetroot -cursor_name left_ptr &

pkill -f /usr/lib/xfce-polkit/xfce-polkit
/usr/lib/xfce-polkit/xfce-polkit &

pkill -f $HOME/.config/dunst/batteryStatus
$HOME/.config/dunst/batteryStatus &

nitrogen --restore &

#########
## Bar ##
#########
pkill polybar
polybar &

pkill nm-applet
nm-applet &

pkill greenclip
greenclip daemon &

pkill -f optimus-manager-qt
optimus-manager-qt &

#################
## Application ##
#################

pkill protonvpn
protonvpn &

pkill Discord
discord --start-minimized &
